# Generated by Django 4.2.4 on 2023-08-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RunSQL("""
                        INSERT INTO store_colllection (title)
                        VALUES ('collection1')
                          ""","""
                          DELETE FROM store_colllection
                          WHERE title='collection1'
                          """)
    ]
